package com.demo.entity;

 

//Generated 2015-2-3 10:43:00 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
* AcctAuthority generated by hbm2java
*/
//左侧 资源树 
@Entity
@Table(name = "demo_resource")
public class Resource  implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2579117424081504224L;
	private Integer id;
	private String name;
 	private Integer orderid;
 
	private String isParent;//是否为 父模块
 
	private String icon;//图标 
	 
	private String urlLocation;//路径
 
	private Integer parentId;//父id
 
	private Integer resourceType;//点击节点 弹出页面 还是 打开一个tab
	
	private String description;//资源描述
	private String createBy;
	private Date createDate;
	private String modifyBy;
	private Date modifyDate;
	
	@Id
	@Column(name = "id", unique = true, nullable = false, length = 36)
 	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	@Column(name = "createBy",length = 36)
	public String getCreateBy() {
		return createBy;
	}
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}
	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "isparent", nullable = false)
	public String getIsParent() {
		return isParent;
	}
	
	public void setIsParent(String isParent) {
		this.isParent = isParent;
	}
	
	@Column(name = "orderid")
	public Integer getOrderid() {
		return orderid;
	}

	public void setOrderid(Integer orderid) {
		this.orderid = orderid;
	}
	
	@Column(name = "icon")
	public String getIcon() {
		return icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}
	
	@Column(name = "urllocation" )
	public String getUrlLocation() {
		return urlLocation;
	}

	public void setUrlLocation(String urlLocation) {
		this.urlLocation = urlLocation;
	}

	@Column(name = "parentid" )
	public Integer getParentId() {
		return parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	@Column(name = "resourcetype")
	public Integer getResourceType() {
		return resourceType;
	}

	public void setResourceType(Integer resourceType) {
		this.resourceType = resourceType;
	}
	@Column(name = "description")
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	
	@Temporal(TemporalType.DATE) 
	@Column(name = "createDate")
	public Date getCreateDate() {
		return createDate;
	}
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	
	@Column(name = "modifyBy",length = 36)
	public String getModifyBy() {
		return modifyBy;
	}
	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}
	
	@Temporal(TemporalType.DATE) 
	@Column(name = "modifyDate")
	public Date getModifyDate() {
		return modifyDate;
	}
	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}
	
	
}
